"""Seed sample books for development and testing.

Adds a curated set of books with embeddings to test the recommendation system.
Safe to run multiple times - skips books that already exist.

IMPORTANT: Uses enhanced embedding format (title, author, description, categories,
publication_year, page_count) as specified in BOOK_RECOMMENDATION.md.
Requires format_book_text() in app.core.embeddings to support these parameters.

Usage:
    python scripts/seed_books.py
"""

import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.core.database import SessionLocal
from app.core.embeddings import create_embedding, format_book_text
from app.services.book_service import create_book, get_book_by_isbn

# Sample books for testing
SAMPLE_BOOKS = [
    {
        "isbn": "9780451524935",
        "isbn13": "9780451524935",
        "title": "1984",
        "author": "George Orwell",
        "description": "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism.",
        "categories": ["Fiction", "Dystopian", "Science Fiction"],
        "page_count": 328,
        "publisher": "Signet Classic",
        "publication_year": 1950,
        "language": "en",
        "average_rating": 4.19,
        "ratings_count": 3847029,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780061120084",
        "isbn13": "9780061120084",
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "description": "A novel about racial injustice and childhood innocence in the American South.",
        "categories": ["Fiction", "Classic", "Historical"],
        "page_count": 324,
        "publisher": "Harper Perennial Modern Classics",
        "publication_year": 1960,
        "language": "en",
        "average_rating": 4.27,
        "ratings_count": 5623456,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780547928227",
        "isbn13": "9780547928227",
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "description": "A fantasy novel about a hobbit's unexpected adventure to reclaim a treasure guarded by a dragon.",
        "categories": ["Fantasy", "Adventure", "Fiction"],
        "page_count": 310,
        "publisher": "Mariner Books",
        "publication_year": 1937,
        "language": "en",
        "average_rating": 4.28,
        "ratings_count": 3456789,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780316769488",
        "isbn13": "9780316769488",
        "title": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "description": "A story about teenage rebellion and alienation narrated by Holden Caulfield.",
        "categories": ["Fiction", "Classic", "Coming of Age"],
        "page_count": 277,
        "publisher": "Little, Brown and Company",
        "publication_year": 1951,
        "language": "en",
        "average_rating": 3.81,
        "ratings_count": 3234567,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780142437239",
        "isbn13": "9780142437239",
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "description": "A romantic novel about manners, marriage, and morality in Georgian England.",
        "categories": ["Romance", "Classic", "Fiction"],
        "page_count": 279,
        "publisher": "Penguin Classics",
        "publication_year": 1813,
        "language": "en",
        "average_rating": 4.28,
        "ratings_count": 4123456,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780142437239-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780553418026",
        "isbn13": "9780553418026",
        "title": "A Brief History of Time",
        "author": "Stephen Hawking",
        "description": "A landmark volume in science writing that explores cosmology and the universe.",
        "categories": ["Science", "Physics", "Non-Fiction"],
        "page_count": 256,
        "publisher": "Bantam",
        "publication_year": 1988,
        "language": "en",
        "average_rating": 4.21,
        "ratings_count": 567890,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780553418026-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780062316097",
        "isbn13": "9780062316097",
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "description": "An exploration of the history of the human species from the Stone Age to the modern age.",
        "categories": ["History", "Non-Fiction", "Anthropology"],
        "page_count": 443,
        "publisher": "Harper",
        "publication_year": 2011,
        "language": "en",
        "average_rating": 4.39,
        "ratings_count": 1234567,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780062073488",
        "isbn13": "9780062073488",
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "description": "A philosophical novel about a shepherd's journey to find treasure and discover his destiny.",
        "categories": ["Fiction", "Philosophy", "Adventure"],
        "page_count": 197,
        "publisher": "HarperOne",
        "publication_year": 1988,
        "language": "en",
        "average_rating": 3.90,
        "ratings_count": 2987654,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780062073488-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780441172719",
        "isbn13": "9780441172719",
        "title": "Dune",
        "author": "Frank Herbert",
        "description": "A science fiction epic about politics, religion, and ecology on the desert planet Arrakis.",
        "categories": ["Science Fiction", "Fantasy", "Epic"],
        "page_count": 688,
        "publisher": "Ace",
        "publication_year": 1965,
        "language": "en",
        "average_rating": 4.25,
        "ratings_count": 1876543,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780345391803",
        "isbn13": "9780345391803",
        "title": "The Hitchhiker's Guide to the Galaxy",
        "author": "Douglas Adams",
        "description": "A comedic science fiction series following Arthur Dent's intergalactic adventures.",
        "categories": ["Science Fiction", "Comedy", "Adventure"],
        "page_count": 224,
        "publisher": "Del Rey",
        "publication_year": 1979,
        "language": "en",
        "average_rating": 4.22,
        "ratings_count": 1654321,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg",
        "data_source": "open_library_google_books",
    },
    # Science Fiction & Fantasy
    {
        "isbn": "9780553293357",
        "isbn13": "9780553293357",
        "title": "Foundation",
        "author": "Isaac Asimov",
        "description": "The first novel in Asimov's Foundation series about the fall and rise of galactic civilizations.",
        "categories": ["Science Fiction", "Space Opera", "Classic"],
        "page_count": 255,
        "publisher": "Spectra",
        "publication_year": 1951,
        "language": "en",
        "average_rating": 4.13,
        "ratings_count": 623451,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780316769174",
        "isbn13": "9780316769174",
        "title": "The Name of the Wind",
        "author": "Patrick Rothfuss",
        "description": "The first book in the Kingkiller Chronicle, following the legend of Kvothe.",
        "categories": ["Fantasy", "Epic Fantasy", "Adventure"],
        "page_count": 662,
        "publisher": "DAW Books",
        "publication_year": 2007,
        "language": "en",
        "average_rating": 4.52,
        "ratings_count": 987654,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780316769174-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780765326355",
        "isbn13": "9780765326355",
        "title": "The Way of Kings",
        "author": "Brandon Sanderson",
        "description": "Epic fantasy about honor, war, and magic in a world of storms.",
        "categories": ["Fantasy", "Epic Fantasy", "High Fantasy"],
        "page_count": 1007,
        "publisher": "Tor Books",
        "publication_year": 2010,
        "language": "en",
        "average_rating": 4.64,
        "ratings_count": 876543,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780765326355-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780441569595",
        "isbn13": "9780441569595",
        "title": "Neuromancer",
        "author": "William Gibson",
        "description": "A cyberpunk novel about a washed-up computer hacker hired for one last job.",
        "categories": ["Science Fiction", "Cyberpunk", "Thriller"],
        "page_count": 271,
        "publisher": "Ace",
        "publication_year": 1984,
        "language": "en",
        "average_rating": 3.88,
        "ratings_count": 456789,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780441569595-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780765348784",
        "isbn13": "9780765348784",
        "title": "Ender's Game",
        "author": "Orson Scott Card",
        "description": "A military science fiction novel about a child genius trained to fight an alien invasion.",
        "categories": ["Science Fiction", "Military SF", "Young Adult"],
        "page_count": 324,
        "publisher": "Tor Books",
        "publication_year": 1985,
        "language": "en",
        "average_rating": 4.30,
        "ratings_count": 1876543,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780765348784-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780441007318",
        "isbn13": "9780441007318",
        "title": "The Left Hand of Darkness",
        "author": "Ursula K. Le Guin",
        "description": "A science fiction novel exploring gender and society on an alien world.",
        "categories": ["Science Fiction", "Anthropological SF", "Classic"],
        "page_count": 304,
        "publisher": "Ace",
        "publication_year": 1969,
        "language": "en",
        "average_rating": 4.07,
        "ratings_count": 345678,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780441007318-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780345342966",
        "isbn13": "9780345342966",
        "title": "A Game of Thrones",
        "author": "George R.R. Martin",
        "description": "The first book in A Song of Ice and Fire series, a tale of power, betrayal, and dragons.",
        "categories": ["Fantasy", "Epic Fantasy", "Dark Fantasy"],
        "page_count": 694,
        "publisher": "Bantam",
        "publication_year": 1996,
        "language": "en",
        "average_rating": 4.44,
        "ratings_count": 2345678,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780345342966-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780060850524",
        "isbn13": "9780060850524",
        "title": "Brave New World",
        "author": "Aldous Huxley",
        "description": "A dystopian novel about a technologically advanced society without freedom.",
        "categories": ["Science Fiction", "Dystopian", "Classic"],
        "page_count": 268,
        "publisher": "Harper Perennial Modern Classics",
        "publication_year": 1932,
        "language": "en",
        "average_rating": 3.99,
        "ratings_count": 1765432,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780441013593",
        "isbn13": "9780441013593",
        "title": "Do Androids Dream of Electric Sheep?",
        "author": "Philip K. Dick",
        "description": "A science fiction novel exploring what it means to be human in a post-apocalyptic world.",
        "categories": ["Science Fiction", "Dystopian", "Philosophical"],
        "page_count": 210,
        "publisher": "Del Rey",
        "publication_year": 1968,
        "language": "en",
        "average_rating": 4.08,
        "ratings_count": 567890,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780441013593-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780553381689",
        "isbn13": "9780553381689",
        "title": "The Handmaid's Tale",
        "author": "Margaret Atwood",
        "description": "A dystopian novel about a totalitarian theocracy and the oppression of women.",
        "categories": ["Dystopian", "Science Fiction", "Feminist"],
        "page_count": 311,
        "publisher": "Anchor",
        "publication_year": 1985,
        "language": "en",
        "average_rating": 4.12,
        "ratings_count": 1987654,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780553381689-L.jpg",
        "data_source": "open_library_google_books",
    },
    # Mystery & Thriller
    {
        "isbn": "9780307949486",
        "isbn13": "9780307949486",
        "title": "The Girl with the Dragon Tattoo",
        "author": "Stieg Larsson",
        "description": "A gripping mystery thriller about a journalist and a hacker investigating a decades-old disappearance.",
        "categories": ["Mystery", "Thriller", "Crime"],
        "page_count": 465,
        "publisher": "Vintage Crime/Black Lizard",
        "publication_year": 2005,
        "language": "en",
        "average_rating": 4.14,
        "ratings_count": 3123456,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780307949486-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780062073556",
        "isbn13": "9780062073556",
        "title": "Gone Girl",
        "author": "Gillian Flynn",
        "description": "A psychological thriller about a marriage gone terribly wrong.",
        "categories": ["Thriller", "Mystery", "Psychological"],
        "page_count": 415,
        "publisher": "Crown Publishing Group",
        "publication_year": 2012,
        "language": "en",
        "average_rating": 4.05,
        "ratings_count": 2987654,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780062073556-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780062024039",
        "isbn13": "9780062024039",
        "title": "And Then There Were None",
        "author": "Agatha Christie",
        "description": "Ten strangers are lured to an island where they're accused of murder and killed one by one.",
        "categories": ["Mystery", "Classic", "Thriller"],
        "page_count": 272,
        "publisher": "William Morrow Paperbacks",
        "publication_year": 1939,
        "language": "en",
        "average_rating": 4.27,
        "ratings_count": 1765432,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780062024039-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780307387899",
        "isbn13": "9780307387899",
        "title": "The Da Vinci Code",
        "author": "Dan Brown",
        "description": "A mystery thriller following symbologist Robert Langdon as he investigates a murder.",
        "categories": ["Thriller", "Mystery", "Adventure"],
        "page_count": 454,
        "publisher": "Anchor",
        "publication_year": 2003,
        "language": "en",
        "average_rating": 3.92,
        "ratings_count": 2456789,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780307387899-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780743273565",
        "isbn13": "9780743273565",
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "description": "A classic American novel about wealth, love, and the American Dream in the 1920s.",
        "categories": ["Classic", "Literary Fiction", "Romance"],
        "page_count": 180,
        "publisher": "Scribner",
        "publication_year": 1925,
        "language": "en",
        "average_rating": 3.93,
        "ratings_count": 4567890,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
        "data_source": "open_library_google_books",
    },
    # Literary Fiction
    {
        "isbn": "9780679783268",
        "isbn13": "9780679783268",
        "title": "One Hundred Years of Solitude",
        "author": "Gabriel García Márquez",
        "description": "A landmark of magical realism chronicling the Buendía family over seven generations.",
        "categories": ["Literary Fiction", "Magical Realism", "Classic"],
        "page_count": 417,
        "publisher": "Harper Perennial Modern Classics",
        "publication_year": 1967,
        "language": "en",
        "average_rating": 4.09,
        "ratings_count": 987654,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780679783268-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780140449136",
        "isbn13": "9780140449136",
        "title": "Crime and Punishment",
        "author": "Fyodor Dostoevsky",
        "description": "A psychological drama about a man who commits murder and grapples with guilt.",
        "categories": ["Classic", "Psychological", "Literary Fiction"],
        "page_count": 671,
        "publisher": "Penguin Classics",
        "publication_year": 1866,
        "language": "en",
        "average_rating": 4.20,
        "ratings_count": 765432,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780140449136-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780679732242",
        "isbn13": "9780679732242",
        "title": "The Remains of the Day",
        "author": "Kazuo Ishiguro",
        "description": "A meditation on dignity, regret, and missed opportunities through an English butler's memoir.",
        "categories": ["Literary Fiction", "Historical", "Drama"],
        "page_count": 258,
        "publisher": "Vintage International",
        "publication_year": 1989,
        "language": "en",
        "average_rating": 4.06,
        "ratings_count": 345678,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780679732242-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780375507250",
        "isbn13": "9780375507250",
        "title": "The Road",
        "author": "Cormac McCarthy",
        "description": "A post-apocalyptic tale of a father and son's journey through a devastated America.",
        "categories": ["Literary Fiction", "Post-Apocalyptic", "Drama"],
        "page_count": 287,
        "publisher": "Vintage",
        "publication_year": 2006,
        "language": "en",
        "average_rating": 3.98,
        "ratings_count": 876543,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780375507250-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780143039433",
        "isbn13": "9780143039433",
        "title": "The Kite Runner",
        "author": "Khaled Hosseini",
        "description": "A powerful story of friendship, betrayal, and redemption set in Afghanistan.",
        "categories": ["Literary Fiction", "Historical", "Drama"],
        "page_count": 371,
        "publisher": "Riverhead Books",
        "publication_year": 2003,
        "language": "en",
        "average_rating": 4.32,
        "ratings_count": 2345678,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780143039433-L.jpg",
        "data_source": "open_library_google_books",
    },
    # Non-Fiction: Science & History
    {
        "isbn": "9780385537858",
        "isbn13": "9780385537858",
        "title": "Thinking, Fast and Slow",
        "author": "Daniel Kahneman",
        "description": "A groundbreaking tour of the mind exploring the two systems that drive human thinking.",
        "categories": ["Psychology", "Non-Fiction", "Science"],
        "page_count": 499,
        "publisher": "Farrar, Straus and Giroux",
        "publication_year": 2011,
        "language": "en",
        "average_rating": 4.17,
        "ratings_count": 567890,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780385537858-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780393347777",
        "isbn13": "9780393347777",
        "title": "Guns, Germs, and Steel",
        "author": "Jared Diamond",
        "description": "An exploration of why some societies prospered while others did not.",
        "categories": ["History", "Anthropology", "Non-Fiction"],
        "page_count": 528,
        "publisher": "W. W. Norton & Company",
        "publication_year": 1997,
        "language": "en",
        "average_rating": 4.00,
        "ratings_count": 456789,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780393347777-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780374533557",
        "isbn13": "9780374533557",
        "title": "Thinking in Bets",
        "author": "Annie Duke",
        "description": "A former poker champion's guide to making smarter decisions when stakes are high.",
        "categories": ["Business", "Psychology", "Non-Fiction"],
        "page_count": 276,
        "publisher": "Portfolio",
        "publication_year": 2018,
        "language": "en",
        "average_rating": 4.08,
        "ratings_count": 123456,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780804139298",
        "isbn13": "9780804139298",
        "title": "The Power of Habit",
        "author": "Charles Duhigg",
        "description": "An exploration of the science behind why we do what we do in life and business.",
        "categories": ["Psychology", "Self-Help", "Non-Fiction"],
        "page_count": 371,
        "publisher": "Random House",
        "publication_year": 2012,
        "language": "en",
        "average_rating": 4.09,
        "ratings_count": 765432,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780385504201",
        "isbn13": "9780385504201",
        "title": "The God Delusion",
        "author": "Richard Dawkins",
        "description": "A critique of religion and argument for atheism from an evolutionary biologist.",
        "categories": ["Philosophy", "Science", "Non-Fiction"],
        "page_count": 464,
        "publisher": "Mariner Books",
        "publication_year": 2006,
        "language": "en",
        "average_rating": 3.96,
        "ratings_count": 345678,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780385504201-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780143127796",
        "isbn13": "9780143127796",
        "title": "Educated",
        "author": "Tara Westover",
        "description": "A memoir about growing up in a survivalist family and pursuing education.",
        "categories": ["Memoir", "Biography", "Non-Fiction"],
        "page_count": 334,
        "publisher": "Random House",
        "publication_year": 2018,
        "language": "en",
        "average_rating": 4.49,
        "ratings_count": 1876543,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780143127796-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780307887894",
        "isbn13": "9780307887894",
        "title": "The Immortal Life of Henrietta Lacks",
        "author": "Rebecca Skloot",
        "description": "The story of Henrietta Lacks and the immortal cell line that revolutionized medicine.",
        "categories": ["Biography", "Science", "Non-Fiction"],
        "page_count": 381,
        "publisher": "Crown",
        "publication_year": 2010,
        "language": "en",
        "average_rating": 4.23,
        "ratings_count": 987654,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg",
        "data_source": "open_library_google_books",
    },
    # Business & Self-Help
    {
        "isbn": "9780062301239",
        "isbn13": "9780062301239",
        "title": "Atomic Habits",
        "author": "James Clear",
        "description": "A practical guide to building good habits and breaking bad ones.",
        "categories": ["Self-Help", "Business", "Non-Fiction"],
        "page_count": 320,
        "publisher": "Avery",
        "publication_year": 2018,
        "language": "en",
        "average_rating": 4.37,
        "ratings_count": 1234567,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780062301239-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9781501111105",
        "isbn13": "9781501111105",
        "title": "The 7 Habits of Highly Effective People",
        "author": "Stephen R. Covey",
        "description": "A classic guide to personal and professional effectiveness.",
        "categories": ["Self-Help", "Business", "Non-Fiction"],
        "page_count": 381,
        "publisher": "Simon & Schuster",
        "publication_year": 1989,
        "language": "en",
        "average_rating": 4.14,
        "ratings_count": 876543,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781501111105-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780735211292",
        "isbn13": "9780735211292",
        "title": "Atomic Habits",
        "author": "James Clear",
        "description": "Practical strategies for building good habits and achieving remarkable results.",
        "categories": ["Self-Help", "Productivity", "Non-Fiction"],
        "page_count": 320,
        "publisher": "Avery",
        "publication_year": 2018,
        "language": "en",
        "average_rating": 4.37,
        "ratings_count": 1345678,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780812981605",
        "isbn13": "9780812981605",
        "title": "Thinking in Systems",
        "author": "Donella H. Meadows",
        "description": "A primer on how to understand and work with complex systems.",
        "categories": ["Science", "Business", "Non-Fiction"],
        "page_count": 240,
        "publisher": "Chelsea Green Publishing",
        "publication_year": 2008,
        "language": "en",
        "average_rating": 4.17,
        "ratings_count": 234567,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780812981605-L.jpg",
        "data_source": "open_library_google_books",
    },
    # Horror & Dark Fiction
    {
        "isbn": "9780385121675",
        "isbn13": "9780385121675",
        "title": "The Shining",
        "author": "Stephen King",
        "description": "A horror novel about a family isolated in a haunted hotel during winter.",
        "categories": ["Horror", "Thriller", "Supernatural"],
        "page_count": 447,
        "publisher": "Doubleday",
        "publication_year": 1977,
        "language": "en",
        "average_rating": 4.23,
        "ratings_count": 1234567,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780385121675-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780140186390",
        "isbn13": "9780140186390",
        "title": "Frankenstein",
        "author": "Mary Shelley",
        "description": "The classic tale of a scientist who creates a monster with tragic consequences.",
        "categories": ["Horror", "Gothic", "Classic"],
        "page_count": 280,
        "publisher": "Penguin Classics",
        "publication_year": 1818,
        "language": "en",
        "average_rating": 3.83,
        "ratings_count": 1567890,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780140186390-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780143107545",
        "isbn13": "9780143107545",
        "title": "Dracula",
        "author": "Bram Stoker",
        "description": "The quintessential vampire novel about Count Dracula's attempt to move from Transylvania to England.",
        "categories": ["Horror", "Gothic", "Classic"],
        "page_count": 418,
        "publisher": "Penguin Classics",
        "publication_year": 1897,
        "language": "en",
        "average_rating": 4.00,
        "ratings_count": 987654,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780143107545-L.jpg",
        "data_source": "open_library_google_books",
    },
    # Young Adult
    {
        "isbn": "9780439023481",
        "isbn13": "9780439023481",
        "title": "The Hunger Games",
        "author": "Suzanne Collins",
        "description": "A dystopian novel about a televised fight to the death in a post-apocalyptic nation.",
        "categories": ["Young Adult", "Dystopian", "Science Fiction"],
        "page_count": 374,
        "publisher": "Scholastic Press",
        "publication_year": 2008,
        "language": "en",
        "average_rating": 4.32,
        "ratings_count": 7654321,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780439023481-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780439064873",
        "isbn13": "9780439064873",
        "title": "Harry Potter and the Sorcerer's Stone",
        "author": "J.K. Rowling",
        "description": "The first book in the Harry Potter series about a young wizard discovering his magical heritage.",
        "categories": ["Fantasy", "Young Adult", "Adventure"],
        "page_count": 309,
        "publisher": "Scholastic",
        "publication_year": 1997,
        "language": "en",
        "average_rating": 4.47,
        "ratings_count": 8765432,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780439064873-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780062237507",
        "isbn13": "9780062237507",
        "title": "Divergent",
        "author": "Veronica Roth",
        "description": "A dystopian novel about a society divided into factions based on virtues.",
        "categories": ["Young Adult", "Dystopian", "Science Fiction"],
        "page_count": 487,
        "publisher": "Katherine Tegen Books",
        "publication_year": 2011,
        "language": "en",
        "average_rating": 4.15,
        "ratings_count": 3456789,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780062237507-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780141346137",
        "isbn13": "9780141346137",
        "title": "The Fault in Our Stars",
        "author": "John Green",
        "description": "A heart-wrenching story about two teenagers who meet in a cancer support group.",
        "categories": ["Young Adult", "Romance", "Contemporary"],
        "page_count": 313,
        "publisher": "Dutton Books",
        "publication_year": 2012,
        "language": "en",
        "average_rating": 4.19,
        "ratings_count": 4567890,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780141346137-L.jpg",
        "data_source": "open_library_google_books",
    },
    # Historical Fiction
    {
        "isbn": "9780385490818",
        "isbn13": "9780385490818",
        "title": "All the Light We Cannot See",
        "author": "Anthony Doerr",
        "description": "A WWII novel about a blind French girl and a German boy whose paths collide.",
        "categories": ["Historical Fiction", "War", "Literary Fiction"],
        "page_count": 531,
        "publisher": "Scribner",
        "publication_year": 2014,
        "language": "en",
        "average_rating": 4.32,
        "ratings_count": 1876543,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780385490818-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780385333849",
        "isbn13": "9780385333849",
        "title": "The Book Thief",
        "author": "Markus Zusak",
        "description": "A story about a young girl living in Nazi Germany who steals books and shares them.",
        "categories": ["Historical Fiction", "Young Adult", "War"],
        "page_count": 552,
        "publisher": "Alfred A. Knopf",
        "publication_year": 2005,
        "language": "en",
        "average_rating": 4.37,
        "ratings_count": 2345678,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780385333849-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780307947727",
        "isbn13": "9780307947727",
        "title": "The Nightingale",
        "author": "Kristin Hannah",
        "description": "A tale of two sisters in France during World War II and their fight for survival.",
        "categories": ["Historical Fiction", "War", "Drama"],
        "page_count": 440,
        "publisher": "St. Martin's Press",
        "publication_year": 2015,
        "language": "en",
        "average_rating": 4.55,
        "ratings_count": 1567890,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780307947727-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780143125761",
        "isbn13": "9780143125761",
        "title": "The Underground Railroad",
        "author": "Colson Whitehead",
        "description": "A reimagining of the Underground Railroad as an actual railroad beneath the Southern soil.",
        "categories": ["Historical Fiction", "Literary Fiction", "Alternate History"],
        "page_count": 320,
        "publisher": "Anchor",
        "publication_year": 2016,
        "language": "en",
        "average_rating": 4.03,
        "ratings_count": 678901,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780143125761-L.jpg",
        "data_source": "open_library_google_books",
    },
    # Contemporary Fiction
    {
        "isbn": "9780374292799",
        "isbn13": "9780374292799",
        "title": "Normal People",
        "author": "Sally Rooney",
        "description": "A story about the complex relationship between two Irish teenagers.",
        "categories": ["Contemporary", "Literary Fiction", "Romance"],
        "page_count": 273,
        "publisher": "Hogarth",
        "publication_year": 2018,
        "language": "en",
        "average_rating": 3.91,
        "ratings_count": 876543,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780374292799-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780316769488",
        "isbn13": "9780316769488",
        "title": "Where the Crawdads Sing",
        "author": "Delia Owens",
        "description": "A mystery about a marsh girl raised in isolation who becomes a suspect in a murder.",
        "categories": ["Mystery", "Contemporary", "Literary Fiction"],
        "page_count": 384,
        "publisher": "G.P. Putnam's Sons",
        "publication_year": 2018,
        "language": "en",
        "average_rating": 4.46,
        "ratings_count": 2345678,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780812968255",
        "isbn13": "9780812968255",
        "title": "Project Hail Mary",
        "author": "Andy Weir",
        "description": "A lone astronaut must save humanity after waking up with amnesia on a spaceship.",
        "categories": ["Science Fiction", "Space Opera", "Thriller"],
        "page_count": 476,
        "publisher": "Ballantine Books",
        "publication_year": 2021,
        "language": "en",
        "average_rating": 4.52,
        "ratings_count": 987654,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780812968255-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780316015844",
        "isbn13": "9780316015844",
        "title": "Twilight",
        "author": "Stephenie Meyer",
        "description": "A romance between a teenage girl and a vampire in the Pacific Northwest.",
        "categories": ["Young Adult", "Romance", "Paranormal"],
        "page_count": 498,
        "publisher": "Little, Brown Books for Young Readers",
        "publication_year": 2005,
        "language": "en",
        "average_rating": 3.62,
        "ratings_count": 5876543,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780316015844-L.jpg",
        "data_source": "open_library_google_books",
    },
    # Philosophy & Classics
    {
        "isbn": "9780486280615",
        "isbn13": "9780486280615",
        "title": "Meditations",
        "author": "Marcus Aurelius",
        "description": "The personal writings of the Roman Emperor, a foundational text in Stoic philosophy.",
        "categories": ["Philosophy", "Classic", "Non-Fiction"],
        "page_count": 112,
        "publisher": "Dover Publications",
        "publication_year": 180,
        "language": "en",
        "average_rating": 4.23,
        "ratings_count": 345678,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780486280615-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780679720201",
        "isbn13": "9780679720201",
        "title": "The Stranger",
        "author": "Albert Camus",
        "description": "A philosophical novel about absurdism following a man who commits murder.",
        "categories": ["Philosophy", "Classic", "Literary Fiction"],
        "page_count": 123,
        "publisher": "Vintage International",
        "publication_year": 1942,
        "language": "en",
        "average_rating": 3.99,
        "ratings_count": 987654,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780679720201-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780143105428",
        "isbn13": "9780143105428",
        "title": "Siddhartha",
        "author": "Hermann Hesse",
        "description": "A spiritual journey of self-discovery set in ancient India.",
        "categories": ["Philosophy", "Spiritual", "Classic"],
        "page_count": 152,
        "publisher": "Penguin Classics",
        "publication_year": 1922,
        "language": "en",
        "average_rating": 4.03,
        "ratings_count": 765432,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780143105428-L.jpg",
        "data_source": "open_library_google_books",
    },
    {
        "isbn": "9780679783268",
        "isbn13": "9780679783268",
        "title": "The Brothers Karamazov",
        "author": "Fyodor Dostoevsky",
        "description": "A philosophical novel exploring faith, doubt, and morality through a family drama.",
        "categories": ["Classic", "Philosophy", "Literary Fiction"],
        "page_count": 796,
        "publisher": "Farrar, Straus and Giroux",
        "publication_year": 1880,
        "language": "en",
        "average_rating": 4.33,
        "ratings_count": 456789,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780679783268-L.jpg",
        "data_source": "open_library_google_books",
    },
]


def seed_books():
    """Seed sample books into the database."""
    db = SessionLocal()
    books_added = 0
    books_skipped = 0

    try:
        print("=" * 70)
        print("SEEDING SAMPLE BOOKS")
        print("=" * 70)
        print(f"\nProcessing {len(SAMPLE_BOOKS)} books...\n")

        for i, book_data in enumerate(SAMPLE_BOOKS, 1):
            # Check if book already exists
            existing = get_book_by_isbn(db, book_data["isbn"])
            if existing:
                print(f"[{i}/{len(SAMPLE_BOOKS)}] ⏭️  {book_data['title']} (already exists)")
                books_skipped += 1
                continue

            # Create embedding from book text using enhanced format
            # Enhanced format includes: title, author, description, categories, year, page_count
            book_text = format_book_text(
                title=book_data["title"],
                author=book_data["author"],
                description=book_data["description"],
                categories=book_data.get("categories"),
                publication_year=book_data.get("publication_year"),
                page_count=book_data.get("page_count"),
            )
            embedding = create_embedding(book_text)

            # Create book
            create_book(
                db=db,
                isbn=book_data["isbn"],
                isbn13=book_data.get("isbn13"),
                title=book_data["title"],
                author=book_data["author"],
                description=book_data["description"],
                categories=book_data["categories"],
                page_count=book_data.get("page_count"),
                publisher=book_data.get("publisher"),
                publication_year=book_data.get("publication_year"),
                language=book_data.get("language"),
                average_rating=book_data.get("average_rating"),
                ratings_count=book_data.get("ratings_count"),
                cover_url=book_data["cover_url"],
                embedding=embedding,
                data_source=book_data.get("data_source", "open_library_google_books"),
            )

            print(f"[{i}/{len(SAMPLE_BOOKS)}] ✅ {book_data['title']} by {book_data['author']}")
            books_added += 1

        db.commit()

        print("\n" + "=" * 70)
        print("SEEDING COMPLETE")
        print("=" * 70)
        print(f"✅ Added: {books_added} books")
        print(f"⏭️  Skipped: {books_skipped} books (already exist)")
        print(f"📚 Total: {books_added + books_skipped} books in database")
        print("=" * 70)

        return books_added

    except Exception as e:
        db.rollback()
        print(f"\n❌ Error during seeding: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_books()
